version: 2
jobs:
    build:
        machine: true
        working_directory: ~/app
        
        steps:
            - checkout
            
            - run:
                name: Build docker image
                command: docker build -t  contanerized-react-app-production .
                
            - run:
                name: Push to heroku
                command: |
                    docker login --username=$HEROKU_LOKIN --password=$HEROKU_TOKEN registry.heroku.com
                    docker tag contanerized-react-app-production registry.heroku.com/contanerized-react-app-production/web
                    docker push registry.heroku.com/contanerized-react-app-production/web
