version: 2
jobs:
    build:
        machine: true
        working_directory: ~/app
        
        steps:
            - checkout
            
            - run:
                name: Build docker image
                command: docker build -t  pipeline-app-docker .
                
            - run:
                name: Push to heroku
                command: |
                    docker login --username=$HEROKU_LOGIN --password=$HEROKU_TOKEN registry.heroku.com
                    docker tag pipeline-app-docker registry.heroku.com/pipeline-app-docker/web
                    docker push registry.heroku.com/pipeline-app-docker/web
                    docker release registry.heroku.com/pipeline-app-docker/web
